# Generated by Django 5.1.5 on 2025-02-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='State',
            field=models.CharField(blank=True, choices=[('chennai', 'Chennai'), ('coimbatore', 'Coimbatore'), ('madurai', 'Madurai'), ('tiruchirappalli', 'Tiruchirappalli'), ('salem', 'Salem'), ('tirunelveli', 'Tirunelveli'), ('vellore', 'Vellore'), ('thoothukudi', 'Thoothukudi'), ('kancheepuram', 'Kancheepuram'), ('erode', 'Erode'), ('karur', 'Karur'), ('dharmapuri', 'Dharmapuri'), ('thanjavur', 'Thanjavur'), ('virudhunagar', 'Virudhunagar'), ('nagapattinam', 'Nagapattinam'), ('rameswaram', 'Rameswaram'), ('kanyakumari', 'Kanyakumari'), ('krishnagiri', 'Krishnagiri'), ('tiruvarur', 'Tiruvarur'), ('cuddalore', 'Cuddalore'), ('pudukkottai', 'Pudukkottai')], max_length=50),
        ),
    ]
